### ISSUE TITLE
fix(rdkit): descriptors_reference still documents Descriptors.FractionCsp3 (broken after #213)

### ISSUE THREAD

**Issue by Divyansh151005** [K-Dense-AI/claude-scientific-skills#242]
### Area

Skill content (SKILL.md / references / scripts)

### Skill name

rdkit

### What happened

PR #213 fixed `skills/rdkit/scripts/molecular_properties.py` to use `Lipinski.FractionCSP3`, but the reference docs still teach the old names. Against RDKit 2026.03.5:

```python
Descriptors.FractionCsp3(mol)
# AttributeError: module 'rdkit.Chem.Descriptors' has no attribute 'FractionCsp3'

rdMolDescriptors.CalcFractionCsp3(mol)
# AttributeError: ... Did you mean: 'CalcFractionCSP3'?
```

Affected spots:
- `skills/rdkit/references/descriptors_reference.md` — `Descriptors.FractionCsp3` (section + diversity example)
- `skills/rdkit/references/api_reference.md` — `rdMolDescriptors.CalcFractionCsp3`

### What you expected instead

Document the working APIs:
- `Descriptors.FractionCSP3` / `Lipinski.FractionCSP3`
- `rdMolDescriptors.CalcFractionCSP3`

### Steps to reproduce

```bash
uv run --with rdkit python -c "from rdkit.Chem import Descriptors, Chem; Descriptors.FractionCsp3(Chem.MolFromSmiles('CCO'))"
```

### Before submitting

- [x] I searched existing issues and this is not a duplicate.
- [x] This is not a security vulnerability.

I'll open a PR to finish the #213 doc correction.
